### ISSUE TITLE
Doctring ERROR: module 'ast' has no attribute 'unparse'

### ISSUE THREAD

**Issue by gcaria** [pixelneo/vim-python-docstring#24]
Hi,
after some environment changes (which I am unable to track down) I am not getting this error when using `:Docstring` in vim.

```
Doctring ERROR: module 'ast' has no attribute 'unparse'
```

Do you have any suggestion on how to debug this?
I've tried opening python and calling `ast.unparse` but that does not give me an error.

**Comment by pixelneo** [comment]
Hello, you can start by removing [this try/except](https://github.com/pixelneo/vim-python-docstring/blob/master/python/pydocstring.py#L275). 

It will fail and show you the whole traceback.

**Comment by gcaria** [comment]
Sorry for the slow reply, this is what I get with the full traceback:

```
Error detected while processing function vimpythondocstring#Full:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.vim/bundle/vim-python-docstring/autoload/../python/pydocstring.py", line 265, in full_docstring
    self.obj_controller.write_docstring(print_hints=print_hints)
  File "/home/ubuntu/.vim/bundle/vim-python-docstring/autoload/../python/pydocstring.py", line 210, in write_docstring
    args, returns, yields, raises = self._process_tree(tree)
  File "/home/ubuntu/.vim/bundle/vim-python-docstring/autoload/../python/pydocstring.py", line 202, in _process_tree
    v.visit(tree)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/ubuntu/.vim/bundle/vim-python-docstring/autoload/../python/asthelper.py", line 113, in visit_FunctionDef
    self._handle_functions(node)
  File "/home/ubuntu/.vim/bundle/vim-python-docstring/autoload/../python/asthelper.py", line 88, in _handle_functions
    type_hint = ast.unparse(arg.annotation)
AttributeError: module 'ast' has no attribute 'unparse'
```

**Comment by pixelneo** [comment]
Honestly, I don't know it seems to me like an issue with the `ast` module. I suggest trying it out with different python version (3.9.13).
